# .github/workflows/upload-readme.yml
name: Upload README via SSH

on:
  push:
    paths:
      - 'README.md'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # No need to write out the key to disk; this action can consume it directly.
      - name: Copy README via SCP action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WSL_SSH_HOST }}
          port: 22
          username: alan
          key: ${{ secrets.WSL_SSH_KEY }}
          source: "README.md"
          target: "/home/alan/remote-dir/"

