# .github/workflows/upload-readme.yml
name: Upload README via SSH

on:
  push:
    paths:
      - 'README.md'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Install your private key
      - name: Set up SSH key
        run: |
          mkdir -p "${HOME}/.ssh"
          echo "${{ secrets.WSL_SSH_KEY }}" > "${HOME}/.ssh/id_rsa"
          chmod 600 "${HOME}/.ssh/id_rsa"

      # 2) Copy via scp
      - name: Copy README via scp
        run: |
          scp -o StrictHostKeyChecking=no \
              -i "${HOME}/.ssh/id_rsa" \
              -P 22 \
              README.md \
              alan@${{ secrets.WSL_SSH_HOST }}:/home/alan/remote-dir/README.md

