# .github/workflows/upload-readme.yml
name: Upload README via SSH

on:
  push:
    paths:
      - 'README.md'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # install your private key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WSL_SSH_KEY }}" > ~/.ssh/github_wsl
          chmod 600 ~/.ssh/github_wsl

      # actually copy
      - name: Copy README to WSL
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.WSL_SSH_HOST }}     # e.g. your public IP or dynamic DNS
          port: 22
          username: alan
          key_path: ~/.ssh/github_wsl
          source: "README.md"
          target: "/home/alan/remote-dir/README.md"

